# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Deploy API Reference"

on:
  push:
    branches:
      - "2.3.x"

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: "Build API References Pages"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        branch:
          - "1.23.x"
          - "2.0.x"
          - "2.1.x"
          - "2.2.x"
          - "2.3.x"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ matrix.branch }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240" # v2
        with:
          coverage: "none"
          php-version: "8.1"
          extensions: mbstring
          tools: composer:v2

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "Install ApiGen dependencies"
        working-directory: "apigen"
        run: "composer install --no-interaction --no-progress"

      - name: "Run ApiGen"
        run: "apigen/vendor/bin/apigen -c apigen/apigen.neon --output docs/${{ matrix.branch }} -- src"

      - name: "Copy favicon"
        run: "cp apigen/favicon.png docs/favicon.png"

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: docs-${{ matrix.branch }}
          path: docs/*

  merge:
    name: "Merge docs"
    needs: build

    runs-on: "ubuntu-latest"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: docs-*
          path: docs
          merge-multiple: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: 'docs'

  deploy:
    needs: merge

    # from https://github.com/actions/deploy-pages

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
