# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Backward Compatibility"

on:
  pull_request:
  push:
    branches:
      - "2.3.x"

permissions:
  contents: read

jobs:
  backward-compatibility:
    name: "Backward Compatibility"

    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # v2
        with:
          coverage: "none"
          php-version: "8.3"

      - name: "Install dependencies"
        run: "composer install --no-dev --no-interaction --no-progress --no-suggest"

      - name: "Install BackwardCompatibilityCheck"
        run: "composer global require --dev roave/backward-compatibility-check"

      - name: "Check"
        run: '"$(composer global config bin-dir --absolute)/roave-backward-compatibility-check"'
