# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Backward Compatibility"

on:
  pull_request:
  push:
    branches:
      - "2.3.x"

permissions:
  contents: read

jobs:
  backward-compatibility:
    name: "Backward Compatibility"

    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1" # v2
        with:
          coverage: "none"
          php-version: "8.3"

      - name: "Install dependencies"
        run: "composer install --no-dev --no-interaction --no-progress --no-suggest"

      - name: "Install BackwardCompatibilityCheck"
        run: "composer global require --dev roave/backward-compatibility-check"

      - name: "Check"
        run: '"$(composer global config bin-dir --absolute)/roave-backward-compatibility-check"'
