# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Merge maintained branch

on:
  push:
    branches:
      - "1.22.x"

jobs:
  merge:
    name: Merge branch
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: "Merge branch"
        uses: everlytic/branch-merge@c4a244dc23143f824ae6c022a10732566cb8e973 # 1.1.5
        with:
          github_token: "${{ secrets.PHPSTAN_BOT_TOKEN }}"
          source_ref: ${{ github.ref }}
          target_branch: '1.23.x'
          commit_message_template: 'Merge branch {source_ref} into {target_branch}'
