# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Create release"

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@98b12822c5dc6bad335d1d60d920cb69831b9c5d # v4.8.0
        with:
          myToken: ${{ secrets.PHPSTAN_BOT_TOKEN }}

      - name: "Create release"
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
